I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/screens.rpy", line 426, in prepare_screen
    screen file_slots(title):
  File "game/screens.rpy", line 426, in prepare
    screen file_slots(title):
Exception: A screen named game_menu does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\bootstrap.py", line 306, in bootstrap
    renpy.main.main()
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\main.py", line 523, in main
    run(restart)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\main.py", line 90, in run
    renpy.display.screen.prepare_screens()
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\screen.py", line 873, in prepare_screens
    s.ast.prepare_screen()
  File "game/screens.rpy", line 426, in prepare_screen
    screen file_slots(title):
  File "game/screens.rpy", line 426, in prepare
    screen file_slots(title):
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\sl2\slast.py", line 1592, in prepare
    raise Exception("A screen named {} does not exist.".format(self.target))
Exception: A screen named game_menu does not exist.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
PlayTrainer 1.0
Thu Nov 29 02:21:37 2018
